# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: project
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5435:5432
    restart: on-failure:3